TILESIZE = 64

WIDTH = 400
HEIGHT = 400
FPS = 60

HITBOX_OFFSET = {
	'player': -26,
	'object': -40,
	'invisible': 0}

BAR_HEIGHT = 20
HEALTH_BAR_WIDTH = 200
ENERGY_BAR_WIDTH = 140
ITEM_BOX_SIZE = 80
UI_FONT = 'graphics/test/font/joystix.ttf'
UI_FONT_SIZE = 18

WATER_COLOUR = '#71ddee'
UI_BG_COLOUR = '#222222'
UI_BORDER_COLOUR = '#111111'
TEXT_COLOUR = '#EEEEEE'

HEALTH_COLOUR = 'red'
ENERGY_COLOUR = 'lightblue'
UI_BORDER_COLOUR_ACTIVE = 'gold'

TEXT_COLOUR_SELECTED = '#111111'
BAR_COLOUR = '#EEEEEE'
BAR_COLOUR_SELECTED = '#111111'
UPGRADE_BG_COLOUR_SELECTED = '#EEEEEE'